### PR TITLE
circleci: use docker so we can test things locally

### PR DESCRIPTION
**Pull request by djs55**
Signed-off-by: David Scott <dave@recoil.org>

### CODE REVIEW

**Comment by talex5** [comment]
I enabled ocaml-ci to see if that could help (it also generates a Dockerfile for you), but it says there is no solution for any version of OCaml.

I see that the `Dockerfile` doesn't build `qcow-tool`. Is that still supposed to be working?

I tried changing the version constraint in `qcow-tool.opam` to `"qcow" {= version}` so that the CI could pin both to `dev`, but it still didn't work.

**Comment by djs55** [comment]
@talex5 thanks for taking a look -- I'll fiddle with it a bit and see if I can make it happy!

**Comment by djs55** [comment]
@talex5 is it possible to run the planning phase of `ocaml-ci` locally?

**Comment by talex5** [comment]
This should do it:
```
git clone --recursive https://github.com/ocurrent/ocaml-ci.git
cd ocaml-ci
dune exec -- ocaml-ci-local /path/to/ocaml-qcow
```

Then browse to http://localhost:8080. You might want to edit `service/conf.ml` to enable more versions in the `Dev` config.

However, an easier way to run the solver is:

```
opam install opam-0install
opam pin add -yn qcow.dev . && opam pin add -yn qcow-tool.dev .
opam-0install qcow qcow-tool
```

That will search across all OCaml versions, but you can also fix one with e.g.

```
opam-0install qcow qcow-tool ocaml.4.05.0
```

**Comment by djs55** [comment]
Woohoo, we now have a green CI! A fast `ocaml-ci` and a slow CircleCI. I might disable the slow CircleCI.

**Pull request merged**
