### PR TITLE
connect no longer returns a result type

### PR DESCRIPTION
**Pull request by hannesm**
needs https://github.com/xapi-project/nbd/pull/28

tests run on my laptop... but I've no clue about this library, code review would be appreciated.

I also modified in lib_test Qemu.create to return `t io` instead of `(`Ok t) io`, there are likely more return types which can be adjusted (not sure why connect calls read, and I've to handle these errors manually, but previously it also failed hard if an error occured; maybe connect should call some read_internal which doesn't return an ``Error`).

### CODE REVIEW

**Comment by hannesm** [comment]
travis is happy after 511 tests in 20 minutes :)

**Comment by yomimono** [comment]
We have other users who are pinning master of ocaml-qcow in the mirage2 universe, so we should probably merge this into a separate mirage3 branch which we pin from mirage-dev.

**Comment by hannesm** [comment]
SGTM, feel free to cherry-pick and put into a mirage-dev branch here... and as mentioned earlier, any code review would be appreciated (since I haven't used qcow at all yet, and have no plan to use it)

**Comment by avsm** [comment]
> We have other users who are pinning master of ocaml-qcow in the mirage2 universe

Who is doing this? I'd like to cut a release for them and then turn the master branch into mirage3 branch

**Comment by hannesm** [comment]
hyperkit used to pin qcow-format (but does no longer https://github.com/docker/hyperkit/pull/64) -- please also have in mind that a modified nbd is needed (see https://github.com/xapi-project/nbd/pull/28) -- ,a possible solution is to fork nbd to mirage organisation and develop on mirage/nbd master for MirageOS3?

**Comment by yomimono** [comment]
Yes, I was thinking of hyperkit, so my comment (and concern!) is now deprecated. :)

**Pull request merged**
